"use strict";
var Tick;
var Team;
(function (Team) {
    Team[Team["Spectators"] = -1] = "Spectators";
    Team[Team["Red"] = 0] = "Red";
    Team[Team["Blue"] = 1] = "Blue";
})(Team || (Team = {}));
var Emote;
(function (Emote) {
    Emote[Emote["Normal"] = 0] = "Normal";
    Emote[Emote["Pain"] = 1] = "Pain";
    Emote[Emote["Happy"] = 2] = "Happy";
    Emote[Emote["Surprise"] = 3] = "Surprise";
    Emote[Emote["Angry"] = 4] = "Angry";
    Emote[Emote["Blink"] = 5] = "Blink";
})(Emote || (Emote = {}));
var Weapon;
(function (Weapon) {
    Weapon[Weapon["Hammer"] = 0] = "Hammer";
    Weapon[Weapon["Pistol"] = 1] = "Pistol";
    Weapon[Weapon["Shotgun"] = 2] = "Shotgun";
    Weapon[Weapon["Grenade"] = 3] = "Grenade";
    Weapon[Weapon["Rifle"] = 4] = "Rifle";
    Weapon[Weapon["Ninja"] = 5] = "Ninja";
})(Weapon || (Weapon = {}));
var Sound;
(function (Sound) {
    Sound[Sound["GunFire"] = 0] = "GunFire";
    Sound[Sound["ShotgunFire"] = 1] = "ShotgunFire";
    Sound[Sound["GrenadeFire"] = 2] = "GrenadeFire";
    Sound[Sound["HammerFire"] = 3] = "HammerFire";
    Sound[Sound["HammerHit"] = 4] = "HammerHit";
    Sound[Sound["NinjaFire"] = 5] = "NinjaFire";
    Sound[Sound["GrenadeExplode"] = 6] = "GrenadeExplode";
    Sound[Sound["NinjaHit"] = 7] = "NinjaHit";
    Sound[Sound["RifleFire"] = 8] = "RifleFire";
    Sound[Sound["RifleBounce"] = 9] = "RifleBounce";
    Sound[Sound["WeaponSwitch"] = 10] = "WeaponSwitch";
    Sound[Sound["PlayerPainShort"] = 11] = "PlayerPainShort";
    Sound[Sound["PlayerPainLong"] = 12] = "PlayerPainLong";
    Sound[Sound["BodyLand"] = 13] = "BodyLand";
    Sound[Sound["PlayerAirjump"] = 14] = "PlayerAirjump";
    Sound[Sound["PlayerJump"] = 15] = "PlayerJump";
    Sound[Sound["PlayerDie"] = 16] = "PlayerDie";
    Sound[Sound["PlayerSpawn"] = 17] = "PlayerSpawn";
    Sound[Sound["PlayerSkid"] = 18] = "PlayerSkid";
    Sound[Sound["TeeCry"] = 19] = "TeeCry";
    Sound[Sound["HookLoop"] = 20] = "HookLoop";
    Sound[Sound["HookAttachGround"] = 21] = "HookAttachGround";
    Sound[Sound["HookAttachPlayer"] = 22] = "HookAttachPlayer";
    Sound[Sound["HookNoattach"] = 23] = "HookNoattach";
    Sound[Sound["PickupHealth"] = 24] = "PickupHealth";
    Sound[Sound["PickupArmor"] = 25] = "PickupArmor";
    Sound[Sound["PickupGrenade"] = 26] = "PickupGrenade";
    Sound[Sound["PickupShotgun"] = 27] = "PickupShotgun";
    Sound[Sound["PickupNinja"] = 28] = "PickupNinja";
    Sound[Sound["WeaponSpawn"] = 29] = "WeaponSpawn";
    Sound[Sound["WeaponNoammo"] = 30] = "WeaponNoammo";
    Sound[Sound["Hit"] = 31] = "Hit";
    Sound[Sound["ChatServer"] = 32] = "ChatServer";
    Sound[Sound["ChatClient"] = 33] = "ChatClient";
    Sound[Sound["ChatHighlight"] = 34] = "ChatHighlight";
    Sound[Sound["CtfDrop"] = 35] = "CtfDrop";
    Sound[Sound["CtfReturn"] = 36] = "CtfReturn";
    Sound[Sound["CtfGrabPl"] = 37] = "CtfGrabPl";
    Sound[Sound["CtfGrabEn"] = 38] = "CtfGrabEn";
    Sound[Sound["CtfCapture"] = 39] = "CtfCapture";
    Sound[Sound["Menu"] = 40] = "Menu";
})(Sound || (Sound = {}));
module.exports = this;
